#!/bin/bash

# KAROLINA specific environment variables
CONTAINER="apptainer"
XFFL_LOCAL_TMPDIR="/tmp/"
export APPTAINER_BINDPATH=$SINGULARITY_BINDPATH
export APPTAINERENV_LD_PRELOAD=$SINGULARITYENV_LD_PRELOAD