name: "CI Tests"
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  cli-config:
    name: "Test xffl config command"
    runs-on: ubuntu-24.04
    steps: 
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.13
          cache: pip
          cache-dependency-path: |
            requirements.txt
      - name: "Install Python Dependencies"
        run: |
          python -m pip install -r requirements.txt
      - name: "Build documentation and check for consistency"
        env:
          CHECKSUM: "bac8064ea7b1ab5a20a700831b7c3f609e50da8eb90377c8c79471578b96bd0e"
        run: |
          cd tests/cli
          HASH="$(make checksum-config | tail -n 1)"
          echo "Project checksum is ${HASH}"
          test "${HASH}" == "${CHECKSUM}"
  static-checks:
    name: "xFFL static checks"
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        step: [ "lint" ]
    env:
      TOXENV: ${{ matrix.step }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: pip
          cache-dependency-path: |
            requirements.txt
            lint-requirements.txt
      - name: "Install Python Dependencies and xFFL"
        run: |
          python -m pip install -r requirements.txt
          python -m pip install -r lint-requirements.txt
      - name: "Run xFFL static analysis via Tox"
        run: make format-check