name: "CI Tests"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  cli-config:
    name: "Test xffl config command"
    strategy:
      matrix:
        on: [ "ubuntu-24.04"]
        python: [ "3.9", "3.10", "3.11", "3.12", "3.13" ]
        include:
          - on: "macos-14"
            python: "3.13"
    runs-on: ${{ matrix.on }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.13
          cache: pip
          cache-dependency-path: requirements.txt
      - name: "Install Python Dependencies"
        run: python -m pip install .
      - name: "Create an xffl project using the config option in the CLI."
        env:
          CHECKSUM: "843b063f348dbb16ef8a9d30ecd638613b038d9b386488bab020a1c4fd23d41e"
        run: |
          cd tests/cli
          HASH="$(make checksum-config | tail -n 1)"
          echo "Project checksum is ${HASH}"
          test "${HASH}" == "${CHECKSUM}"
      - name: "Validate project"
        run: |
          cd tests/cli
          make setup
          make generate-project
          xffl run --project test --validate
          make clean
  static-checks:
    name: "xFFL static checks"
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        step: [ "lint" ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: pip
          cache-dependency-path: |
            requirements.txt
            lint-requirements.txt
      - name: "Install Python Dependencies and xFFL"
        run: |
          python -m pip install -r requirements.txt
          python -m pip install -r lint-requirements.txt
      - name: "Run xFFL static analysis"
        run: make format-check codespell-check flake8